name: Retrain and Package Model CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow Project Retraining
        run: |
          cd MLProject
          mlflow run . --no-conda -P n_estimators=120 -P max_depth=6